on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - run: curl -L https://flix.dev/nightly/flix-2021-05-12.jar > flix.jar
    - run: java -jar flix.jar --test *.flix
